-- Add only the catalog fields required by the Phase 4 course and professor APIs.

alter table public.professors
  add column department text,
  add column title text;

alter table public.course_reviews
  add column would_retake boolean;

alter table public.professor_reviews
  add column difficulty integer check (difficulty between 1 and 5),
  add column would_retake boolean;

create table public.course_grade_distributions (
  id integer generated by default as identity primary key,
  course_id integer not null references public.courses(id) on delete cascade,
  term_id integer references public.terms(id) on delete set null,
  grade text not null,
  percentage numeric(5,2) not null check (percentage between 0 and 100)
);

create index course_grade_distributions_course_id_index
  on public.course_grade_distributions (course_id);
