-- Add the interaction tables required by the Phase 5 review APIs.

create table public.course_saves (
  user_id uuid not null references public.users(id) on delete cascade,
  course_id integer not null references public.courses(id) on delete cascade,
  created_at timestamp without time zone not null default now(),
  primary key (user_id, course_id)
);

create table public.professor_review_likes (
  review_id integer not null references public.professor_reviews(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamp without time zone not null default now(),
  primary key (review_id, user_id)
);

create table public.professor_review_reports (
  id integer generated by default as identity primary key,
  review_id integer not null references public.professor_reviews(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  reason text not null check (char_length(trim(reason)) between 1 and 1000),
  created_at timestamp without time zone not null default now(),
  unique (review_id, user_id)
);

create index professor_review_likes_review_id_index
  on public.professor_review_likes (review_id);

create index professor_review_reports_review_id_index
  on public.professor_review_reports (review_id);
