-- Add shared event and activity data required by the dashboard APIs.

alter table public.users
  add column presence_status text not null default 'offline'
    check (presence_status in ('online', 'away', 'offline')),
  add column last_seen_at timestamp without time zone;

create table public.events (
  id integer generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 200),
  type text not null check (type in ('registration', 'deadline', 'class', 'exam', 'study', 'academic', 'social')),
  starts_at timestamp without time zone not null,
  ends_at timestamp without time zone,
  description text,
  location text,
  term_id integer references public.terms(id) on delete set null,
  created_at timestamp without time zone not null default now(),
  check (ends_at is null or ends_at >= starts_at)
);

create table public.activities (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  actor_id uuid references public.users(id) on delete set null,
  type text not null check (char_length(trim(type)) between 1 and 100),
  message text not null check (char_length(trim(message)) between 1 and 500),
  data jsonb not null default '{}'::jsonb,
  created_at timestamp without time zone not null default now()
);

create index events_starts_at_index on public.events (starts_at);
create index activities_user_created_at_index on public.activities (user_id, created_at desc);
