-- Add the posts, comments, likes, and saves tables required by the Phase 8 feed APIs.

create table public.posts (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null check (type in ('schedule', 'review', 'question', 'tip')),
  content text not null check (char_length(trim(content)) between 1 and 5000),
  tags text[] not null default '{}',
  schedule_id integer references public.schedules(id) on delete set null,
  created_at timestamp without time zone not null default now()
);

create table public.post_likes (
  post_id integer not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamp without time zone not null default now(),
  primary key (post_id, user_id)
);

create table public.post_saves (
  post_id integer not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamp without time zone not null default now(),
  primary key (post_id, user_id)
);

create table public.post_comments (
  id integer generated by default as identity primary key,
  post_id integer not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 2000),
  created_at timestamp without time zone not null default now()
);

create index posts_created_at_index on public.posts (created_at desc);
create index posts_user_id_index on public.posts (user_id);
create index post_likes_post_id_index on public.post_likes (post_id);
create index post_saves_post_id_index on public.post_saves (post_id);
create index post_comments_post_id_created_at_index on public.post_comments (post_id, created_at);
