-- Add the notifications table required by the Phase 10 notification APIs.

create table public.notifications (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  actor_id uuid references public.users(id) on delete set null,
  type text not null check (char_length(trim(type)) between 1 and 100),
  message text not null check (char_length(trim(message)) between 1 and 500),
  data jsonb not null default '{}'::jsonb,
  read_at timestamp without time zone,
  created_at timestamp without time zone not null default now()
);

create index notifications_user_id_created_at_index
  on public.notifications (user_id, created_at desc);

create index notifications_user_id_unread_index
  on public.notifications (user_id)
  where read_at is null;
