-- Phase 11: Events RSVP + Study Groups

-- Event RSVPs (many-to-many between users and events)
CREATE TABLE IF NOT EXISTS public.event_rsvps (
  event_id integer NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (event_id, user_id)
);
CREATE INDEX IF NOT EXISTS event_rsvps_user_id_idx ON public.event_rsvps (user_id);

-- Study groups
CREATE TABLE IF NOT EXISTS public.study_groups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(trim(name)) BETWEEN 1 AND 200),
  course_code text,
  description text,
  meeting_time text,
  location text,
  host_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  max_members integer CHECK (max_members IS NULL OR max_members >= 2),
  created_at timestamp without time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS study_groups_host_idx ON public.study_groups (host_user_id);

-- Study group members (many-to-many)
CREATE TABLE IF NOT EXISTS public.study_group_members (
  study_group_id integer NOT NULL REFERENCES public.study_groups(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  joined_at timestamp without time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (study_group_id, user_id)
);
CREATE INDEX IF NOT EXISTS study_group_members_user_idx ON public.study_group_members (user_id);
