-- Study group chat messages. A row represents a single message posted by a
-- group member in a study group's chat. Reuses the existing study_groups and
-- users tables; does not introduce a separate membership system.
CREATE TABLE IF NOT EXISTS public.study_group_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  study_group_id integer NOT NULL REFERENCES public.study_groups(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  content text NOT NULL CHECK (char_length(trim(content)) BETWEEN 1 AND 2000),
  -- Stored as an absolute instant in UTC so the client can render the message
  -- time in the browser's local timezone without any offset compensation.
  created_at timestamptz NOT NULL DEFAULT now()
);
-- Support chronological reads per group (e.g. the 15-day window history
-- queries) as well as membership-scoped queries. Ordering is by created_at, so
-- scoping to a group plus a created_at range uses this index.
CREATE INDEX IF NOT EXISTS study_group_messages_group_idx ON public.study_group_messages (study_group_id, created_at);
CREATE INDEX IF NOT EXISTS study_group_messages_sender_idx ON public.study_group_messages (sender_id);
